export default {
    UPDATE_USER_IN_SLOT: "UPDATE_USER_IN_SLOT",
    UPDATE_SLOT_STATUS: "UPDATE_SLOT_STATUS",
    UPDATE_SLOT_TIMES: "UPDATE_SLOT_TIMES",
    UPDATE_SELECTED_SLOT_TIME: "UPDATE_SELECTED_SLOT_TIME",
    UPDATE_SLOTS_DATA: "UPDATE_SLOTS_DATA",
}